### ISSUE TITLE
getTypeVariableInstantiation argument renaming reversal?

### ISSUE THREAD

**Issue by peterz-dps** [insieme/insieme#54] opened 2015-04-16 15:56 UTC
getTypeVariableInstantiation (https://github.com/insieme/insieme/blob/master/code/core/src/types/type_variable_deduction.cpp#L542) fails for certain cases.

Test IR construct:
```
let fun000 = fun(vector<'res,#l> v4, ('res) -> 'res v5) -> unit {
    v5(v4[0]);
};

let fun001 = fun('a v2) -> 'a {
    return v2;
};

{
    decl vector<int<4>,8> v6 = undefined(type<vector<int<4>,8>>);
    fun000(v6, fun001);
}
```
Debug output from getTypeVariableInstantiation on the call to fun000:
```
 Parameter: [AP(vector<'res,#l>),AP((('res)->'res))]
   Renamed: [AP(vector<'v1,#A>),AP((('v1)->'v1))]
 Arguments: [AP(vector<int<4>,8>),AP((('a)->'a))]
   Mapping: {}
 Renamed Arguments: [AP(vector<int<4>,8>),AP((('v2)->'v2))]
 Constraints: ['v2<:'v1,'v1<:'v2,int<4><:'v1,'v1<:int<4> / {AP(#A)=AP(8)}]
 Solution: {'v2->int<4>,'v1->int<4>/#A->8}
 Terminated with: {'res->int<4>,'v2->int<4>/#l->8}
```
Note that the field argumentRenaming contains a mapping  {'a<->'v2}

**Comment by PeterTh** [comment] 2015-04-16 16:51
@HerbertJordan I have a few questions about this.

My understanding/investigation so far: [Here](https://github.com/insieme/insieme/blob/master/code/core/src/types/type_variable_deduction.cpp#L587-L597) a renaming in arguments is performed, but after the constraint solver derives its solution ({'v2->int<4>,'v1->int<4>/#A->8} in this case) the renaming is only reversed ([here](https://github.com/insieme/insieme/blob/master/code/core/src/types/type_variable_deduction.cpp#L641-L662)) for the RHS of each mapping but not the LHS. Adding a backward application of the renaming to `var` (and not just `substitute`) solves this issue for this particular use case, but it produces problems elsewhere.

Now, the questions:
- Why is this renaming required in the first place?
- Why is the renaming for parameters and each individual argument completely separate? Wouldn't it make sense to rename corresponding types to the same var, even if only to make the constraint solver's job easier?
- How should we go about undoing the renaming on the LHS without breaking functionality? (If undoing that renaming is in fact the correct solution and not merely mitigating a symptom of a more fundamental issue)

**Comment by HerbertJordan** [comment] 2015-04-17 13:14
I guess that there is a simple miss-understanding in the purpose of the function. It computes a type variable substitution for the type variables of a targeted function -- which does not involve any bindings for type variables of the arguments. The fact that some of those turn up in the solution is a mere by-product of the implementation since a last step filtering out unneeded bindings is skipped.

So the result `{'res->int<4>,'v2->int<4>/#l->8}` which is a super-set of the desired solution `{'res->int<4>/#l->8}` and thus a valid solution for the desired purpose. For more details on the type-deduction mechanism see Definition 3.30 in the thesis.

Regarding @PeterTh questions:
- Why renaming?

To prevent invalid variable capturing. If there are the same type variables utilized in the arguments and in the parameters those have to be treated as distinct variables. For instance, calling a function of type `('a,'b,('b)->'b)->'a` with arguments `int<4>`,`bool` and `('a)->'a` would without the re-naming result into the constraints
```
int<4> <: 'a, bool <: 'b, 'b<:'a, 'a<:'b
```
which, due to the antisymmetric nature of the sub-type lattice, implies that `'a = 'b` and a valid  type mapped to those variables would have to be a super-type of `int<4>` and `bool`. But such a type does not exist. Yet, the call is perfectly valid. The error is caused by an invalid identification of the `'a`s in the arguments and parameters which is prevented by proper renaming as it is conducted by the implementation.

- Why renaming parameters individually?

The separation for each parameter has the same reasons as the renaming. A function `('a)->'a` passed as a first argument may be instantiated using a different substitution than a function of the same type passed as a second argument. Using the same mapping for all would over-constraint solutions.

- How to fix?

In my opinion there is nothing to fix. The LHS is not supposed to be renamed. The function has the be used in its intended way by the client code. 

The deduction of type parameters is a local operation per call. You do not obtain all type substitutions in a sub-tree by analyzing a call at its root. In the general case additional constraints (and variables) are contributed by nested calls. To get the type variable substitution of nested calls you will have to instantiate the body of the generic outer function and then continue by obtaining the type variable substitution of the nested calls (naive approach). 

In a better approach, you would circumvent the actual creation of instantiated codes by taking the type substititon obtained from the outer scope, and only apply it on the nested calls interactively along the path towards the point of interest. This is essentially the same with much less overhead. 

A effective implementation would e.g. accept an address to some type variable and then utilize a path visitor to walk from the root node towards the addressed node continuously updating a type substitution whenever passing a call expression.

**Comment by PeterTh** [comment] 2015-04-18 02:27
I see, thanks.

I was fully aware that type parameter deduction is local to each call, and we are already performing the operation on nested calls recursively to arrive at a final solution - which was working adequately. The issue we encountered (and were trying to solve) is specifically related to deducing the concrete type of type variables (or variable int type params) in lambdas passed to higher order functions, such as `fun001` in the opening example.

This concrete issue is exemplified in the simplest way possible in [this unit test](https://github.com/insieme/insieme/blob/cdc655b48ef0585d3044fa13887bf859ad673770/code/core/test/transform/instantiation_test.cc#L322-L347). I can now see (thanks to your explanation) that the way we went about it could potentially be dangerous/invalid when provided with a combination of multiple arguments using the same type variable names while referring to distinct concrete type instantiations. I'll have a look into creating a unit test which tests exactly that case and then working out a real solution from there.

**Comment by HerbertJordan** [comment] 2015-04-18 10:06
I had a look at the example. The given example required 

What troubles me: when you have a call
```
f(a,g)
```
where f and g are generic functions, the current implementation of `instantiateTypes` seems to no only rewrite the function `f` but also the parameter `g`. This is what is tested in the test case. Why should a parameter be effected from the instantiation of a function it is passed to? What if the same parameter would have to be instantiated for two different sets of type parameters?

As I mentioned already in an [earlier thread](https://github.com/insieme/insieme/issues/21#issuecomment-89931167), I am pretty sure that the root of the problem is that what you are trying to accomplish is a data-flow analysis. You need to know which function is passed to which position before being called. While for the examples encountered so far this might be still seem to be within a moderate complexity using ad-hoc solutions -- essentially all you need to do is tracing the passing of parameters -- in the general case a more structured approach should be taken.

For instance, within the CBA framework there is already an analysis ([Functions](https://github.com/insieme/insieme/blob/cdc655b48ef0585d3044fa13887bf859ad673770/code/analysis/include/insieme/analysis/cba/analysis/functions.h)) that determines for an arbitrary expression a set of functions / closures it may evaluate to. Implementing a [facade](https://github.com/insieme/insieme/blob/cdc655b48ef0585d3044fa13887bf859ad673770/code/analysis/include/insieme/analysis/cba/analysis.h) for this analysis avoid a direct dependency to the CBA framework and incurred high compile time overheads should be pretty simple. The major problem is probably the fact that analysis can not be accessed in the core ...

**Comment by PeterTh** [comment] 2015-12-01 17:07
Closing this. Some of the discussion is still relevant, but the original question is answered.

**Closed by PeterTh** 2015-12-01 17:07 UTC
Labels: core, invalid, question
