### ISSUE TITLE
RFC: IR cleanup / review -- preparation - Inspire 1.5

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#29] opened 2015-04-06 13:51 UTC
To simplify future work with the IR a few modifications / cleanup operations should be applied. Please help extending and discussing the following list of issues:
- remove guard expressions from JobExpr; maybe: make job expr a function
- remove int type parameter and replace by generic types and type variables
- introduce let bindings for variable scopes and cleanup operations
- distinguish variables from recursive variables in expressions and types
- resolve class-meta-info problem
- introduction of distinct nodes for type literals
- enforce equality between recursive types and unrolled versions within the node structure / implementation
- make marker nodes transparent or device alternative sharing-breaking facilities
- remove special treatment of references, channels, arrays and vectors in the IR implementation
- extend type system to support user-defined sub-typing relations
- formalizing the life-cycle of objects
- improved support for virtual function resolution

**Comment by PeterTh** [comment] 2015-04-07 08:42
- remove guard expressions from JobExpr; maybe: make job expr a function
The first part of this one is already done, just pending merging because of required OpenCL backend fixes.

**Comment by HerbertJordan** [comment] 2015-04-08 11:21
Elimination of variable numbers ... a long-felt want :+1:

**Comment by LuisAyuso** [comment] 2015-04-09 11:52
Playing to build IR i found 2 things that are pretty annoying:
- Recursive types and Structs, every time you exprect to be dealing with a struct type you might write something like:  type.isa<StructTypePtr>(). the problem is that it might (and will) be a recursive type, then you have to copypaste the 3 lines of code to unroll it. These 3 lines are widely used and copypasted everywhere. Would be nice to force all TagTypes to be recursive by default somehow.
- Marked nodes, similar to the problem mentioned before, would be cool that the marker node does not exist but instead we mark (and unify) the original node (i.e. via extra child) this way when you write something like stmt.isa<ForLoopPtr>() it will be the expected type. I'm afraid that the small utilization of marker nodes might not be showing all the potential places where they are not supported.

**Comment by HerbertJordan** [comment] 2015-04-09 14:19
Very nice - added to the list, thx.

**Comment by PeterTh** [comment] 2015-04-09 14:56
I like the marker idea a lot, this will also allow marking types.

**Comment by LuisAyuso** [comment] 2015-04-10 07:26
what about giving to the list of expressions and list type a first class citizen implementation?

**Comment by HerbertJordan** [comment] 2015-04-10 09:40
As a node type sure. The "Expressions" node type already exists - yet just as a supporting node type for constructing other types of nodes, right? A list of expressions would not be an expression, nor would a list of types be a type.

**Comment by LuisAyuso** [comment] 2015-04-10 10:21
yeap, my question is a little weak. what i mean is that list of expressions can turn into one single expression node by using the encoder. This is not a list of expressions as you said but something like an expressionList. 
This feature is widely used and I somehow find intrusive the use of the encoder to build valid IR. maybe we should think on some standarization (because an expression list is useful), but then it should have its own type, or match vector or array?

**Comment by HerbertJordan** [comment] 2015-04-10 10:29
I'd prefer a minimalistic approach where only things that can not be build out of other components should become language constructs --- like in C++: provide all the means to build good libraries, the rest do with libraries. 

I'd also argue that the special treatment of channel, array, vector, reference types as well as job expressions should be eliminated. The types are nothing more than glorified abstract types and the job expression is a special function. I think we should eliminate those special cases and unify their handling and capabilities.

**Comment by LuisAyuso** [comment] 2015-04-10 10:32
I think once again we are not getting understood. 
so you prefer to have an Expression node that can not be semantically checked because it has no type? I invite you to run semantic checks on the code produced by the backend and see what I mean on the expressions constructed by the encoder.

**Comment by HerbertJordan** [comment] 2015-04-10 10:40
You are talking about the list of expressions we sometimes encode in IR to forward stuff from A to B - right? Those have types ... like every expression ...

You have to consider two things: there are two types of expression list encoders -- the direct encoder, that is type checked and can only list expressions of the same type, and the expression list encoder that can list expressions of arbitrary types. Both have their justification, but neither are supposed to reach the code-generation phase in the backend without being intercepted.

By "the code produced by the backend" you mean the code after the processor? This code should still be semantically valid -- though the assert ensuring this is for sure disabled in the current build for performance reasons, so nobody is checking for this ... has this changed? Are there errors?

**Comment by LuisAyuso** [comment] 2015-04-10 10:54
There are, the backend preprocessor poduces semanticaly invalid code by pasing  expression lists to be "intercepted" afterwards, 
The sad true is that the encoder is used, hidden inside of tools, in every stage of the compiler (including the parser2. using encode for list of expressions without any transformation, check or cast) 
If the expression list is such an important feature maybe, and just maybe, it would make sense to have an expressionList type.

**Comment by LuisAyuso** [comment] 2015-04-14 10:45
What happened to sink and source, is this still a desired feature? should we finish it?

**Comment by LuisAyuso** [comment] 2015-04-14 13:36
Look what i found in another thread: @HerbertJordan 
`vector.init([s,s+1,s+2]` This is the kind of stuff I mean, The only way to write this in IR is with the encoder, no builder. And there is no way in IR to use the list, don't you think that if you want to write this kind of stuff we should give full support first? (btw, this is not even an existing IR construct)

**Comment by HerbertJordan** [comment] 2015-04-15 15:04
Sink and source are already implemented in the core and should be properly covered by the backend. Adding full support is a (probably not so trivial) frontend issue.

@LuisAyuso right, it is called `vector.initPartial` 
https://github.com/insieme/insieme/blob/master/code/core/include/insieme/core/lang/inspire_api/vector.def#L58
You should consider the encode framework as an extended builder. One could, if desired, add support for encoding of lists as well to the builder. In fact, for the implementation of `pickVariant` the builder already utilizes the encoder framework. Furthermore, just because terms are combined into more complex IR structures utilizing the builder does not means that those are not type-checked. There is no special construct involved, protecting *encoded* content from the other. Encoded constructs are also just plain I constructs and covered by all semantic checks.

**Comment by HerbertJordan** [comment] 2015-05-05 12:53
We should also improve the handling of OO features by:
- formalizing the life-cycle of objects
- improved support for virtual function resolution
- integrate member functions in the IR structure instead of annotating it (already mentioned before)

**Comment by LuisAyuso** [comment] 2015-05-07 09:11
Currently we can define read only types and writte only types. Nevertheless these two types do not have constructors, and can be used only by casting or promoting an instance of a pure ref variable.
Does it make sense to have a constructor for this types?  specially sources?
it could use the memlocation, and be something like const-memlocation.

**Comment by HerbertJordan** [comment] 2015-05-07 15:15
Semantically both do not make a lot of sense. While the creation of a pure sink would be a memory location you can write to but never read from is like a black hole (or a /dev/null in the unix world) which you can optimize away; the creation of a pure source of type src<T>-- a memory location initialized once and then only read is equivalent to a value of T where you save the deref operation.

The only use case this could be interesting is when there is a constant big value that should be -- for efficiency reasons -- passed by const-reference / const pointer to a function. And this is a kinda low-level, C specific optimization. We could leaf this to the backend where actual source constructors could be added as an extension and values of type T could be transformed to src<T> with the corresponding constructor and those passed by reference utilizing existing infrastructure.

What do you guys think?

**Comment by PeterTh** [comment] 2015-05-07 19:57
I also can't think of any meaningful use case for pure sinks. 

About pure source types, I wonder if it would make handling const references easier. I feel the latter is related to formalizing object life-cycles, in particular to how we will deal with the C++ prvalue/xvalue concepts in Inspire.

**Comment by LuisAyuso** [comment] 2015-05-08 07:12
I agree that the semantics might not be fully covered by C, especially the sink. But It would provide coherence to the model.

In the case of sources, It does happen in C quite often: Declaration of read memory areas is semanticaly checked in latest compilers when using a R/W pointer and a vector. (i.e. a literal string)
Literal strings will not be declared in the stack and should not be assigned to R/W pointers but W pointers. Therefore we find a match between Read only initialization and Text segment of the process image(http://duartes.org/gustavo/blog/post/anatomy-of-a-program-in-memory/).

**Comment by PeterTh** [comment] 2015-12-01 16:51
Many of these points are accomplished in current master, or superfluous in the new design. Some are still open, but for those separate issues should be created when they become relevant.

**Closed by PeterTh** 2015-12-01 16:51 UTC
Labels: collection, core, enhancement
